[tool.poetry]
name = "repl_nix_tigerbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
async-timeout = "^4.0.2"
discord = "^1.7.0"
youtube_dl = "^2021.12.17"
helpers = "^0.2.0"
PyNaCl = "^1.5.0"
ffmpeg = "^1.4"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
